language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

install:
  - go get -v golang.org/x/tools/cmd/goimports

script:
  - test -z "$(for d in $(go list -f '{{.Dir}}' ./...); do goimports -d $d/*.go | tee /dev/stderr; done)"
  - go test -v ./...
  - go vet ./...
